#!/usr/bin/env python3
"""
Kgotla AI - Cloud Dashboard Generator
Generates daily report from all agent outputs
"""

import json
import os
from datetime import datetime

def generate_daily_report():
    """Generate daily report from all outputs"""
    
    report = f"""# 🎯 Kgotla AI - Daily Report
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC

---

## 📊 Today's Summary

"""
    
    # Check leads
    leads_dir = 'outputs/leads'
    if os.path.exists(leads_dir):
        csv_files = [f for f in os.listdir(leads_dir) if f.endswith('.csv')]
        if csv_files:
            report += f"✅ **Leads Generated:** {len(csv_files)} file(s)\\n"
            report += f"📁 Location: `outputs/leads/`\\n\\n"
    
    # Check content
    content_dir = 'outputs/content'
    if os.path.exists(content_dir):
        txt_files = [f for f in os.listdir(content_dir) if f.endswith('.txt')]
        if txt_files:
            report += f"✅ **Content Generated:** {len(txt_files)} file(s)\\n"
            report += f"📁 Location: `outputs/content/`\\n\\n"
    
    # Check funding
    funding_dir = 'outputs/funding'
    if os.path.exists(funding_dir):
        md_files = [f for f in os.listdir(funding_dir) if f.endswith('.md')]
        if md_files:
            report += f"✅ **Funding Applications:** {len(md_files)} file(s)\\n"
            report += f"📁 Location: `outputs/funding/`\\n\\n"
    
    # Check team
    team_dir = 'outputs/team'
    if os.path.exists(team_dir):
        report += f"✅ **Team Reports:** Available\\n"
        report += f"📁 Location: `outputs/team/`\\n\\n"
    
    # Check website
    website_dir = 'outputs/website'
    if os.path.exists(website_dir):
        report += f"✅ **Website Audit:** Available\\n"
        report += f"📁 Location: `outputs/website/`\\n\\n"
    
    report += f"""---

## 📁 All Your Files

### 📧 Leads
- Location: `outputs/leads/`
- Contains: CSV files with prospects and draft emails

### 📝 Content
- Location: `outputs/content/`
- Contains: LinkedIn posts ready to copy-paste

### 💰 Funding
- Location: `outputs/funding/`
- Contains: Application packages and funding pipeline

### 👥 Team
- Location: `outputs/team/`
- Contains: Progress reports and daily targets

### 🔧 Website
- Location: `outputs/website/`
- Contains: Audit reports and fix guides

---

## 🎯 Priority Actions

1. **🔴 CRITICAL:** Fix SSL/HTTPS on website
   - File: `outputs/website/WEBSITE_FIX_GUIDE.md`

2. **🟠 HIGH:** Submit funding application
   - File: `outputs/funding/APPLICATION_PACKAGE_SEFA.md`

3. **🟡 HIGH:** Contact leads
   - File: `outputs/leads/leads_*.csv`

4. **🟢 MEDIUM:** Post LinkedIn content
   - File: `outputs/content/content_*.txt`

---

## 🔄 How to Access

This report is automatically generated every day at 6:00 AM UTC.

You can access your files from any browser by visiting:
**https://github.com/YOUR_USERNAME/kgotlaai-agents**

---

**Need to run agents now?** 
1. Go to: https://github.com/YOUR_USERNAME/kgotlaai-agents/actions
2. Click "Kgotla AI Daily Agents"
3. Click "Run workflow"

---

*Generated by Kgotla AI Cloud Agents*
"""
    
    # Save report
    with open('DAILY_REPORT.md', 'w') as f:
        f.write(report)
    
    print("✅ Daily report generated: DAILY_REPORT.md")
    return report

if __name__ == '__main__':
    generate_daily_report()
